"""Builder-derived, column-level Lineage: the graph, its exports, and the Manifest.

The Lineage this library emits is derived from the CasePlan, not from the SQL. That is a
deliberate inversion of the obvious design, and the reason is that sqlglot's own
`lineage()` disables qualify's validation internally and degrades silently: an unresolvable
source becomes a placeholder leaf, a star without a schema becomes a leaf named `"*"`, an
unknown subquery scope only logs a warning. Anything built on it would report a
confident-looking graph with holes in it. So builder-derived lineage is AUTHORITATIVE at
runtime, and `sqlglot.lineage` appears only in the test suite as a cross-check - never as
validation.

Node identity is the fully-qualified `db.table.column` a contributor typed in a Declaration.
Nothing re-derives it: `ColumnRef.qualified` is the string, everywhere.

The static Lineage artifact is the git-tracked output of this module. It is derivable from a
Case definition without running anything, regenerated by a command, and diffable in review -
which is the only defence against `Case.variant()`'s action at a distance and against late
Tag-family binding changing a Case nobody edited. Nothing written here carries a timestamp
or a host name for exactly that reason: an artifact that changes when nothing changed is an
artifact reviewers learn to skip.

Everything in this module reads the plan, never the AST and never the SQL text. The plan is
what `compile.build` renders, so the graph describes the statement that will actually run -
including its Filters and its Join path, both of which move numbers without appearing in any
column-to-column mapping a parser could recover.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Sequence

import networkx

from sqlcomposer.declaration import ColumnRef, Registry, Source, TimeBucket
from sqlcomposer.errors import InvalidDeclaration
from sqlcomposer.model import Case, CasePlan, Dimension, Filter, Grain, Metric, ReAggregation

__all__ = [
    "NodeId",
    "ROLE_METRIC",
    "ROLE_DIMENSION",
    "ROLE_FILTER",
    "ROLE_JOIN_KEY",
    "Lineage",
    "node_id",
    "output_id",
    "build",
    "to_text",
    "to_dot",
    "Manifest",
    "manifest_for",
    "manifests_for_reads",
    "trace_through",
    "static_lineage",
    "write_static_lineage",
    "write_manifests",
]

NodeId = str
"""A Lineage node id. Either `db.table.column` for a Source column - identical to
`ColumnRef.qualified` - or `<case name>:<output column>` for a Case's output. The two forms
cannot collide because a Case name may not contain a colon and a qualified column always
contains exactly two dots."""

ROLE_METRIC = "metric"
ROLE_DIMENSION = "dimension"
ROLE_FILTER = "filter"
ROLE_JOIN_KEY = "join_key"
"""Edge `role` values. Every edge carries exactly one, so a reader can ask "which columns
does this number actually come from" and exclude the ones that only joined or narrowed
it."""

_KIND_COLUMN = "column"
_KIND_OUTPUT = "output"
"""Node `kind` values. Private because the contract is the two strings, not these names."""

_ROLE_RANK = {
    ROLE_METRIC: 3,
    ROLE_DIMENSION: 3,
    ROLE_FILTER: 2,
    ROLE_JOIN_KEY: 1,
}
"""A DiGraph holds one edge per ordered pair, so a column that both IS a number and also
narrows it or carries a join has to collapse to a single role. The stronger claim wins: "this
column is the number" outranks "this column only narrowed it", which outranks "this column
only carried a join". Collapsing the other way would let a `dt` that is both the Grain and the
Partition filter print as a filter and read as if the breakdown came from nowhere."""

_MANIFEST_VERSION = 1


@dataclass(frozen=True)
class Lineage:
    """Which Source columns feed each output column of a Case, and the Join path taken.

    `graph` is a `networkx.DiGraph` whose edges point DOWNSTREAM - from a Source column to
    the output that consumes it - so `networkx.ancestors(graph, output)` is the answer to
    "where did this number come from" and the graph reads the same direction as the data.

    Node attributes: every node carries `kind` ("column" or "output"); a column node carries
    `type` (the declared Hive type) and `partition`; an output node carries `role`
    ("dimension" or "metric") and, for a metric, `rule` (its `ReAggregation` value) and
    `native` (the Grain it was rolled up from, or None).

    `rule` and `native` are the live objects - a `ReAggregation` member and a `Grain`, not
    their string forms. The graph is an in-memory structure, and a reader asking whether a
    number rolled up by SUM should be able to compare against `ReAggregation.SUM` rather than
    re-parse a string; the string forms exist only in `to_json`, `to_text` and `to_dot`.

    Edge attributes: `role`, one of the ROLE_ constants; and for a filter edge, `filter`
    (the Filter's name); for a metric edge, `metric` (the Metric's name).

    `path` is the Join path as edge names, recorded because decision 4 requires the chosen
    path to be part of the Lineage - two Join paths between the same Sources give the same
    column-level graph and different numbers.

    Output order is the graph's node insertion order, which `build`, `trace_through` and
    `Manifest.from_json` all preserve. It is `Case.output_names`: Dimensions in Grain order,
    then Metrics sorted by name.
    """

    graph: networkx.DiGraph
    case: str
    path: tuple[str, ...]

    def outputs(self) -> tuple[str, ...]:
        """Every output column name, in the Case's output order."""
        prefix = f"{self.case}:"
        return tuple(
            node[len(prefix) :]
            for node, data in self.graph.nodes(data=True)
            if data.get("kind") == _KIND_OUTPUT and node.startswith(prefix)
        )

    def upstream(self, output_column: str) -> frozenset[NodeId]:
        """Every Source column feeding one output column, transitively.

        Takes the bare output name (`failure_rate`), not the prefixed node id. Includes
        columns reached through Filters and join keys; walk `graph.in_edges(..., data=True)`
        and read each edge's `role` if you want only the measured ones.

        Refuses an output this Case does not publish rather than returning an empty set: an
        empty answer to "where did this number come from" is indistinguishable from a
        misspelled output name, and one of those is a wrong review.
        """
        node = output_id(self.case, output_column)
        if node not in self.graph:
            raise InvalidDeclaration(
                subject=f"{self.case}:{output_column}",
                problem=f"Case {self.case!r} publishes no output column "
                f"{output_column!r}",
                remedy="use one of the names Lineage.outputs() reports",
                outputs=", ".join(self.outputs()) or "(none)",
            )
        return frozenset(
            found
            for found in networkx.ancestors(self.graph, node)
            if self.graph.nodes[found].get("kind") == _KIND_COLUMN
        )

    def downstream(self, column: NodeId) -> frozenset[str]:
        """Every output column of this Case that a given Source column feeds.

        The impact question: "if this warehouse column changes, which numbers move".

        Deliberately asymmetric with `upstream`: a column this Case never reads answers with
        the empty set rather than refusing, because "none of them" is the true answer to the
        impact question and a caller sweeping every column of a changed table would
        otherwise have to guard every call.
        """
        if column not in self.graph:
            return frozenset()
        prefix = f"{self.case}:"
        return frozenset(
            found[len(prefix) :]
            for found in networkx.descendants(self.graph, column)
            if self.graph.nodes[found].get("kind") == _KIND_OUTPUT and found.startswith(prefix)
        )

    def columns(self) -> frozenset[NodeId]:
        """Every Source column node in the graph."""
        return frozenset(
            node
            for node, data in self.graph.nodes(data=True)
            if data.get("kind") == _KIND_COLUMN
        )


def node_id(ref: ColumnRef) -> NodeId:
    """`db.table.column`. Identical to `ColumnRef.qualified`, and exists only so callers
    reading the graph do not have to know that."""
    return ref.qualified


def output_id(case: str, output_column: str) -> NodeId:
    """`<case>:<output column>` - the node id of one of a Case's output columns.

    Refuses a Case name containing a colon. Nothing else in the library enforces that, and
    the whole no-collision argument for this node id scheme rests on it: with two colons in
    play, splitting a node id back into (case, output) stops being unambiguous and a graph
    read from a Manifest starts pointing at the wrong thing.
    """
    if ":" in case:
        raise InvalidDeclaration(
            subject=f"case:{case}",
            problem=f"Case name {case!r} contains a colon, which separates a Case from its "
            "output column in every Lineage node id",
            remedy="rename the Case; a colon makes its node ids ambiguous",
        )
    return f"{case}:{output_column}"


# ======================================================================================
# Building the graph
# ======================================================================================


def _add_column(graph: networkx.DiGraph, ref: ColumnRef) -> NodeId:
    """Add (or find) the node for a Source column, carrying its declared facts."""
    node = node_id(ref)
    if node not in graph:
        graph.add_node(node, kind=_KIND_COLUMN, type=ref.type, partition=ref.partition)
    return node


def _add_edge(
    graph: networkx.DiGraph,
    frm: NodeId,
    to: NodeId,
    *,
    role: str,
    **attrs: Any,
) -> None:
    """Add a downstream edge, keeping the strongest role when one already exists.

    Replaces rather than updates the attribute dict, so a `filter` name cannot survive on an
    edge that has been promoted to a metric edge.
    """
    existing = graph.get_edge_data(frm, to)
    if existing is not None:
        if _ROLE_RANK[existing["role"]] >= _ROLE_RANK[role]:
            return
        graph.remove_edge(frm, to)
    graph.add_edge(frm, to, role=role, **attrs)


def _measured_columns(metric: Metric) -> tuple[ColumnRef, ...]:
    """The columns a Metric actually aggregates, components included.

    Not `Metric.columns`, which also carries the scoped `when`'s columns: those narrow the
    number rather than being it, and the two want different edge roles. A `COUNT(*)` Metric
    returns nothing here - it measures rows, not a column - so its output node carries no
    metric edge at all. That is honest rather than a gap: the Source it counts is named by
    the plan's spine and path, which is what the static artifact's header prints.
    """
    refs: list[ColumnRef] = []
    if metric.column is not None:
        refs.append(metric.column)
    for part in metric.components:
        refs.extend(_measured_columns(part))
    return tuple(refs)


def _scoped_filters(metric: Metric) -> tuple[Filter, ...]:
    """Every `when` Filter scoped to this Metric, components included, first mention first."""
    found: list[Filter] = []
    seen: set[str] = set()
    if metric.when is not None:
        found.append(metric.when)
        seen.add(metric.when.name)
    for part in metric.components:
        for scoped in _scoped_filters(part):
            if scoped.name not in seen:
                found.append(scoped)
                seen.add(scoped.name)
    return tuple(found)


def _sorted_refs(refs: Iterable[ColumnRef]) -> tuple[ColumnRef, ...]:
    """Column refs in qualified-name order, so edge insertion is stable between runs."""
    return tuple(sorted(refs, key=lambda ref: ref.qualified))


def build(registry: Registry, plan: CasePlan) -> Lineage:
    """Derive the Lineage of a planned Case from the plan itself.

    Adds one node per output column and one per Source column the plan reaches, then edges:
    each Metric's measured columns to its output (role `metric`), each Dimension's column to
    its output (role `dimension`), each Case-level Filter's columns to EVERY output (role
    `filter`, because a WHERE clause narrows every number in the Case), each Metric-scoped
    Filter's columns to that Metric's output only (also role `filter`, because it narrows
    rather than measures), and each join key on both sides to every output (role
    `join_key`).

    Reads `plan.dimensions`, `plan.metrics`, `plan.filters` and `plan.path` - never
    `plan.case` - for everything except the Case's name. The plan is what `compile.build`
    renders, so a plan whose Filters differ from its Case's produces a Lineage of the
    statement that will run rather than of the Case that was declared.

    `registry` is taken first by the library-wide convention and is not consulted: every
    fact this graph records is already on the plan, and re-deriving any of it from the
    Registry would let the artifact disagree with the SQL. It stays in the signature because
    resolving a written Source's Manifest belongs here if this ever stops being true.

    Authoritative. Never cross-checked against `sqlglot.lineage` at runtime.
    """
    case_name = plan.case.name
    graph = networkx.DiGraph()

    # Output nodes first and in output order: node insertion order IS `outputs()`.
    for dimension in plan.dimensions:
        _add_output(graph, case_name, dimension.name, role=ROLE_DIMENSION)
    for metric_plan in plan.metrics:
        _add_output(
            graph,
            case_name,
            metric_plan.metric.name,
            role=ROLE_METRIC,
            rule=metric_plan.rule,
            native=metric_plan.native,
        )
    every_output = tuple(
        node
        for node, data in graph.nodes(data=True)
        if data.get("kind") == _KIND_OUTPUT
    )

    for dimension in plan.dimensions:
        target = output_id(case_name, dimension.name)
        for ref in _sorted_refs(dimension.columns):
            _add_edge(graph, _add_column(graph, ref), target, role=ROLE_DIMENSION)

    for metric_plan in plan.metrics:
        metric = metric_plan.metric
        target = output_id(case_name, metric.name)
        for ref in _sorted_refs(_measured_columns(metric)):
            _add_edge(
                graph,
                _add_column(graph, ref),
                target,
                role=ROLE_METRIC,
                metric=metric.name,
            )
        for scoped in _scoped_filters(metric):
            for ref in _sorted_refs(scoped.columns):
                _add_edge(
                    graph,
                    _add_column(graph, ref),
                    target,
                    role=ROLE_FILTER,
                    filter=scoped.name,
                )

    for case_filter in plan.filters:
        for ref in _sorted_refs(case_filter.columns):
            node = _add_column(graph, ref)
            for target in every_output:
                _add_edge(graph, node, target, role=ROLE_FILTER, filter=case_filter.name)

    for step in plan.path:
        for left, right in step.keys:
            for ref in (left, right):
                node = _add_column(graph, ref)
                for target in every_output:
                    _add_edge(graph, node, target, role=ROLE_JOIN_KEY)

    return Lineage(graph=graph, case=case_name, path=plan.join_names)


def _add_output(
    graph: networkx.DiGraph,
    case: str,
    name: str,
    *,
    role: str,
    **attrs: Any,
) -> NodeId:
    """Add one output node, refusing a duplicate output name.

    Two outputs publishing the same name would collapse to one node here and to one INSERT
    column downstream - the Grain already refuses it between Dimensions, but a Metric named
    after a Dimension is only caught here.
    """
    node = output_id(case, name)
    if node in graph:
        raise InvalidDeclaration(
            subject=f"case:{case}",
            problem=f"two output columns of {case!r} are both named {name!r}",
            remedy="rename the Metric, or give the Dimension an explicit `alias=`; output "
            "names are Lineage node ids and INSERT columns",
        )
    graph.add_node(node, kind=_KIND_OUTPUT, role=role, **attrs)
    return node


# ======================================================================================
# Exports
# ======================================================================================


def _rule_text(rule: Any) -> str:
    return rule.value if isinstance(rule, ReAggregation) else str(rule)


def _edge_text(data: dict[str, Any]) -> str:
    """How one edge prints: its role, plus the name that explains it."""
    role = data.get("role", "")
    if role == ROLE_FILTER and data.get("filter"):
        return f"{role} {data['filter']}"
    if role == ROLE_METRIC and data.get("metric"):
        return f"{role} {data['metric']}"
    return role


def _output_text(data: dict[str, Any]) -> str:
    """How one output node prints: its role and, for a Metric, how it was re-aggregated."""
    role = data.get("role", "")
    if role != ROLE_METRIC:
        return role
    native: Grain | None = data.get("native")
    where = str(native) if native is not None else "atomic rows"
    return f"{role} rule={_rule_text(data.get('rule'))} from={where}"


def _path_text(path: Sequence[str]) -> str:
    return " -> ".join(path) or "(direct)"


def _tree_lines(
    graph: networkx.DiGraph,
    node: NodeId,
    depth: int,
    stack: tuple[NodeId, ...],
) -> list[str]:
    """One indented line per contributing column, deepest-last, sorted by node id.

    Recursive because `trace_through` makes the graph deeper than two levels: a column on a
    written Source has the Manifest's own upstream columns hanging off it.
    """
    lines: list[str] = []
    for parent in sorted(graph.predecessors(node)):
        data = graph.edges[parent, node]
        marker = "  (cycle)" if parent in stack else ""
        lines.append(f"{'  ' * depth}{parent}  [{_edge_text(data)}]{marker}")
        if not marker:
            lines.extend(_tree_lines(graph, parent, depth + 1, stack + (parent,)))
    return lines


def to_text(lineage: Lineage, output_column: str | None = None) -> str:
    """A text tree of where each output column comes from.

    One block per output column, or just the named one. Children are sorted by node id so
    the output is stable enough to paste into a review comment, and each edge prints its
    role, so a column that only narrows a number is visibly different from one that is the
    number. Ends with the Join path.

    ASCII only, and indentation rather than box-drawing characters: this is printed to a
    Windows terminal as often as to a Unix one, and a `UnicodeEncodeError` in the middle of
    a refusal is a worse outcome than a plainer tree.
    """
    outputs = lineage.outputs()
    if output_column is not None:
        if output_column not in outputs:
            raise InvalidDeclaration(
                subject=f"{lineage.case}:{output_column}",
                problem=f"Case {lineage.case!r} publishes no output column "
                f"{output_column!r}",
                remedy="use one of the names Lineage.outputs() reports",
                outputs=", ".join(outputs) or "(none)",
            )
        outputs = (output_column,)

    lines = [lineage.case]
    for name in outputs:
        node = output_id(lineage.case, name)
        lines.append(f"  {name}  [{_output_text(lineage.graph.nodes[node])}]")
        contributors = _tree_lines(lineage.graph, node, 2, (node,))
        lines.extend(contributors or ["    (no declared column feeds this output)"])
    lines.append(f"  join path: {_path_text(lineage.path)}")
    return "\n".join(lines)


def _dot_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _dot_label(*parts: str) -> str:
    """A DOT label: each part escaped, then joined by a literal backslash-n."""
    return "\\n".join(_dot_escape(part) for part in parts if part)


_DOT_EDGE_STYLE = {
    ROLE_METRIC: 'style="solid"',
    ROLE_DIMENSION: 'style="solid", color="gray40"',
    ROLE_FILTER: 'style="dashed"',
    ROLE_JOIN_KEY: 'style="dotted", color="gray60"',
}


def to_dot(lineage: Lineage, name: str = "lineage") -> str:
    """The graph as a DOT string.

    A string, not a file and not a rendered image: DOT is a text format, so there is no
    graphviz dependency to install and the output diffs. Source columns and outputs are
    given different shapes, and edge roles become edge styles.

    Column nodes come out sorted and outputs in output order, and the edge list is sorted,
    so re-exporting an unchanged Lineage is a byte-identical file.
    """
    graph = lineage.graph
    lines = [f'digraph "{_dot_escape(name)}" {{']
    lines.append("  rankdir=LR;")
    lines.append(
        f'  graph [label="{_dot_label(lineage.case, "join path: " + _path_text(lineage.path))}",'
        ' labelloc="t"];'
    )
    lines.append('  node [fontname="Helvetica", fontsize=10];')

    for node in sorted(lineage.columns()):
        data = graph.nodes[node]
        shape = "box3d" if data.get("partition") else "box"
        label = _dot_label(node, str(data.get("type", "")))
        lines.append(f'  "{_dot_escape(node)}" [shape="{shape}", label="{label}"];')

    for output in lineage.outputs():
        node = output_id(lineage.case, output)
        data = graph.nodes[node]
        label = _dot_label(output, _output_text(data))
        lines.append(f'  "{_dot_escape(node)}" [shape="ellipse", label="{label}"];')

    for frm, to in sorted(graph.edges()):
        data = graph.edges[frm, to]
        style = _DOT_EDGE_STYLE.get(data.get("role", ""), 'style="solid"')
        lines.append(
            f'  "{_dot_escape(frm)}" -> "{_dot_escape(to)}" '
            f'[{style}, label="{_dot_label(_edge_text(data))}"];'
        )

    lines.append("}")
    return "\n".join(lines)


# ======================================================================================
# The Manifest
# ======================================================================================


def _grain_to_json(grain: Grain | None) -> list[dict[str, Any]] | None:
    """A Grain as its Dimensions' qualified columns, buckets and aliases.

    Not just the output names: a Dimension's identity is the column it reads, and a Grain
    read back from output names alone could not be compared against another Grain by column,
    which is exactly what the re-grain check does.
    """
    if grain is None:
        return None
    return [
        {
            "column": dimension.column.qualified,
            "bucket": dimension.bucket.value if dimension.bucket is not None else None,
            "alias": dimension.alias,
            "note": dimension.note,
        }
        for dimension in grain.dimensions
    ]


def _grain_from_json(data: Any, registry: Registry) -> Grain | None:
    if data is None:
        return None
    return Grain(
        dimensions=tuple(
            Dimension(
                column=registry.resolve_column(item["column"]),
                bucket=TimeBucket(item["bucket"]) if item.get("bucket") else None,
                alias=item.get("alias"),
                note=item.get("note", ""),
            )
            for item in data
        )
    )


def _lineage_to_json(lineage: Lineage) -> dict[str, Any]:
    nodes: list[dict[str, Any]] = []
    for node, data in lineage.graph.nodes(data=True):
        if data.get("kind") == _KIND_COLUMN:
            nodes.append(
                {
                    "id": node,
                    "kind": _KIND_COLUMN,
                    "type": data.get("type"),
                    "partition": bool(data.get("partition")),
                }
            )
        else:
            entry: dict[str, Any] = {"id": node, "kind": _KIND_OUTPUT, "role": data.get("role")}
            if "rule" in data:
                entry["rule"] = _rule_text(data["rule"])
            if "native" in data:
                entry["native"] = _grain_to_json(data["native"])
            nodes.append(entry)
    edges: list[dict[str, Any]] = []
    for frm, to, data in lineage.graph.edges(data=True):
        edge: dict[str, Any] = {"from": frm, "to": to, "role": data.get("role")}
        for key in ("filter", "metric"):
            if key in data:
                edge[key] = data[key]
        edges.append(edge)
    return {
        "case": lineage.case,
        "path": list(lineage.path),
        "nodes": nodes,
        "edges": edges,
    }


def _lineage_from_json(data: dict[str, Any], registry: Registry) -> Lineage:
    graph = networkx.DiGraph()
    for entry in data["nodes"]:
        node = entry["id"]
        if entry.get("kind") == _KIND_COLUMN:
            # Re-resolving is the point of taking a Registry: a column that has left the
            # Declarations refuses here rather than tracing to something that is gone. The
            # declared type and partitioning are then taken from TODAY's Declaration - a
            # retyped column is Drift, and verify.py owns that report.
            ref = registry.resolve_column(node)
            graph.add_node(node, kind=_KIND_COLUMN, type=ref.type, partition=ref.partition)
        else:
            attrs: dict[str, Any] = {"kind": _KIND_OUTPUT, "role": entry.get("role")}
            if "rule" in entry:
                attrs["rule"] = ReAggregation(entry["rule"])
            if "native" in entry:
                attrs["native"] = _grain_from_json(entry["native"], registry)
            graph.add_node(node, **attrs)
    for entry in data["edges"]:
        attrs = {"role": entry["role"]}
        for key in ("filter", "metric"):
            if key in entry:
                attrs[key] = entry[key]
        graph.add_edge(entry["from"], entry["to"], **attrs)
    return Lineage(graph=graph, case=data["case"], path=tuple(data["path"]))


@dataclass(frozen=True)
class Manifest:
    """The Lineage a written Source carries.

    This is what lets a later Case reading a written table trace through it to the true
    upstream Sources instead of stopping at the written table - and what lets a re-grain
    check know the Grain the stored numbers were written at.

    `source` is the written Source's qualified name, as a string rather than a Source object
    so a Manifest round-trips through JSON without the Registry.

    `lineage.case` is the producing Case, so the Manifest's own output nodes are
    `<producing case>:<column>` while the table's columns are `<source>.<column>`. Those are
    the two ends `trace_through` splices together, matched by output name - which is the
    same match `Registry.metric_behind` makes, and the reason `Case.output_names` has to
    stay stable.
    """

    source: str
    written_by: str
    written_at: Grain
    lineage: Lineage

    def to_json(self) -> str:
        """Serialise. The written Grain is recorded as its Dimensions' qualified columns,
        buckets and aliases, and the graph as a node/edge list with every attribute - a
        Manifest read back must answer the same questions as the one that was written.

        Indented and in graph order rather than sorted: a Manifest is a checked-in artifact,
        and stable ordering plus one key per line is what makes its diff readable."""
        return json.dumps(
            {
                "version": _MANIFEST_VERSION,
                "source": self.source,
                "written_by": self.written_by,
                "written_at": _grain_to_json(self.written_at),
                "lineage": _lineage_to_json(self.lineage),
            },
            indent=2,
        )

    @classmethod
    def from_json(cls, text: str, registry: Registry) -> Manifest:
        """Read a Manifest back, re-resolving every column node through the Registry.

        Raises `UndeclaredColumn` or `UndeclaredSource` if the Declarations have moved since
        the Manifest was written - a Manifest that no longer type-checks against the
        Declarations is worse than no Manifest, because it would trace to columns that are
        gone.
        """
        data = json.loads(text)
        version = data.get("version")
        if version != _MANIFEST_VERSION:
            raise InvalidDeclaration(
                subject=f"manifest:{data.get('source', '(unknown)')}",
                problem=f"Manifest format version {version!r} is not readable by this "
                f"library, which writes version {_MANIFEST_VERSION}",
                remedy="regenerate the Manifest with the current version of the composer",
            )
        registry.source(data["source"])  # refuses a Manifest for a table nobody declares
        return cls(
            source=data["source"],
            written_by=data["written_by"],
            written_at=_grain_from_json(data["written_at"], registry) or Grain(),
            lineage=_lineage_from_json(data["lineage"], registry),
        )


def manifest_for(registry: Registry, plan: CasePlan, target: Source) -> Manifest:
    """The Manifest a write of this plan into `target` should carry.

    `written_at` is the plan's Case's Grain. Raises `InvalidDeclaration` when `target` does
    not declare a column for every output name, because a Manifest that describes columns
    the table does not have will mis-trace the first Case that reads it.

    Note which Grain that is: the PRODUCING Case's Grain, whose Dimensions point at the
    upstream Sources' columns, not at `target`'s own. `Registry.native_grain` is the one that
    re-points a written Source's Grain at its own columns, and a re-grain check wants that
    one. This records where the numbers came from; that one records what they are now keyed
    by.
    """
    missing = tuple(name for name in plan.output_names if not target.has(name))
    if missing:
        raise InvalidDeclaration(
            subject=f"source:{target.qualified}",
            problem=f"Case {plan.case.name!r} publishes {', '.join(missing)}, which "
            f"{target.qualified} does not declare",
            remedy="regenerate the Declaration for the written table, or correct the "
            "Case's Metric names and Grain so they match its columns",
            declared=", ".join(column.name for column in target.columns) or "(none)",
        )
    return Manifest(
        source=target.qualified,
        written_by=plan.case.name,
        written_at=plan.case.grain,
        lineage=build(registry, plan),
    )


def _graft(
    graph: networkx.DiGraph,
    upstream: networkx.DiGraph,
    output_node: NodeId,
    onto: NodeId,
) -> None:
    """Copy everything feeding `output_node` in `upstream` into `graph`, landing on `onto`.

    The Manifest's output node is not copied: it IS the written table's column, and keeping
    both would put two nodes in the graph for one number.
    """
    feeding = networkx.ancestors(upstream, output_node)
    inside = feeding | {output_node}
    for node in feeding:
        if node not in graph:
            graph.add_node(node, **dict(upstream.nodes[node]))
    for frm, to, data in upstream.edges(data=True):
        if frm not in inside or to not in inside:
            continue
        attrs = dict(data)
        role = attrs.pop("role")
        _add_edge(
            graph,
            onto if frm == output_node else frm,
            onto if to == output_node else to,
            role=role,
            **attrs,
        )


def trace_through(lineage: Lineage, manifests: Sequence[Manifest]) -> Lineage:
    """Splice each written Source's Manifest into a Lineage that reads it.

    Where `lineage` has a column node on a written Source, the matching Manifest's graph is
    grafted in so that the leaves become the true upstream Sources. Manifests that match no
    node in `lineage` are ignored; a written Source with no Manifest is left as a leaf, which
    is honest - the trace genuinely stops there. So is a column of a written Source that its
    producing Case does not publish (a Partition column the write adds, say): no Manifest
    output matches it, and it stays a leaf.

    Runs to a fixed point, so a chain of written Sources - A feeds B feeds the Case - traces
    all the way back in one call, and each (Manifest, column) pair is grafted at most once so
    a cyclic set of Manifests terminates instead of spinning.

    Returns a new Lineage; does not mutate the one passed in.
    """
    graph = lineage.graph.copy()
    by_source: dict[str, Manifest] = {}
    for manifest in manifests:
        by_source.setdefault(manifest.source, manifest)

    grafted: set[tuple[str, NodeId]] = set()
    changed = True
    while changed:
        changed = False
        for node in [
            found
            for found, data in list(graph.nodes(data=True))
            if data.get("kind") == _KIND_COLUMN
        ]:
            source_name, _, column_name = node.rpartition(".")
            manifest = by_source.get(source_name)
            if manifest is None or (source_name, node) in grafted:
                continue
            produced = output_id(manifest.lineage.case, column_name)
            if produced not in manifest.lineage.graph:
                continue
            grafted.add((source_name, node))
            _graft(graph, manifest.lineage.graph, produced, node)
            changed = True

    return Lineage(graph=graph, case=lineage.case, path=lineage.path)


# ======================================================================================
# The git-tracked artifact
# ======================================================================================


def manifests_for_reads(registry: Registry, case: Case) -> tuple[Manifest, ...]:
    """A Manifest for every written Source this Case reads, transitively, sorted by Source.

    The hop that makes decision 7's two halves one thing. A Manifest needs a plan and a
    plan needs no `run_date`, so the Manifests a static artifact traces through are
    derivable from the Declarations alone - exactly like the artifact itself. Nothing here
    runs anything or reads a file.

    Transitive because a written Source can be read by the Case that writes another one:
    `Registry.writing_case` answers who wrote each Source, and following that answer from
    the producer's own Sources reaches the atomic tables at the end of the chain. A cycle -
    which `write.plan` refuses as a statement order - terminates here on the visited set
    rather than spinning.

    Raises whatever planning a producing Case raises. That is wanted: an artifact that
    traced through a Case which no longer compiles would describe numbers nobody can produce.
    """
    from sqlcomposer import compile as compile_module  # local: see static_lineage

    found: dict[str, Manifest] = {}
    pending = [case]
    seen_cases = {case.name}
    while pending:
        reading = pending.pop()
        for source in sorted(reading.sources(registry), key=lambda item: item.qualified):
            producer = registry.writing_case(source)
            if producer is None or source.qualified in found:
                continue
            producer_plan = compile_module.plan(registry, producer)
            found[source.qualified] = manifest_for(registry, producer_plan, source)
            if producer.name not in seen_cases:
                seen_cases.add(producer.name)
                pending.append(producer)
    return tuple(found[key] for key in sorted(found))


def static_lineage(registry: Registry, case: Case) -> str:
    """The git-tracked text artifact for one Case.

    Derivable from the Case definition with nothing running: the resolved Metric family, the
    Grain, the Filters, the chosen Join path and the column-level tree. Regenerating this
    and diffing it is what makes `Case.variant()` and late Tag binding reviewable - both of
    them change a Case's SQL from a file that does not mention it.

    Goes through `compile.plan`, which means it also runs every refusal - an ambiguous Join
    path or an unprovable re-grain raises here rather than producing an artifact. That is
    wanted: an artifact regenerated in CI is then also a check that every declared Case still
    compiles.

    A Case that reads a written Source gets TWO trees. The first is what the statement
    literally reads, stopping at the written table's own columns; the second traces through
    that table's Manifest to the Sources the numbers actually came from. Both are here on
    purpose: the first is the SQL under review, and the second is the answer to "where did
    this number come from", which is the question decision 7 exists for. Without it the
    committed record for a Case reading a written table stops at a table rather than at
    Sources - and editing the producing Case's Filters, which is exactly the action at a
    distance this artifact defends against, would leave the file byte-identical.

    No `run_date` is bound anywhere, including in the Manifests. Planning resolves Tags, the
    Join path and the re-grain proofs, none of which look at a deferred value, so a Case
    whose Filters hold a `RunDate` has a static Lineage just like any other - only rendering
    it to SQL would refuse.
    """
    # Local import: compile imports this module at module scope, so the dependency has to
    # run in this direction only when someone actually asks for an artifact.
    from sqlcomposer import compile as compile_module

    plan = compile_module.plan(registry, case)
    lineage = build(registry, plan)
    manifests = manifests_for_reads(registry, case)

    lines = [
        f"case: {case.name}",
        f"grain: {case.grain}",
        f"spine: {plan.spine.qualified}",
        f"sources: {', '.join(source.qualified for source in plan.sources)}",
        f"join path: {_path_text(lineage.path)}",
        f"metrics: "
        f"{', '.join(item.metric.name for item in plan.metrics) or '(none)'}",
        f"filters: {', '.join(item.name for item in plan.filters) or '(none)'}",
    ]
    if case.writes_to is not None:
        lines.append(f"writes: {case.writes_to.qualified}")
    if manifests:
        lines.append(
            "traces through: "
            + ", ".join(
                f"{manifest.source} (written by {manifest.written_by})"
                for manifest in manifests
            )
        )
    if case.note:
        lines.append(f"note: {case.note}")
    lines.append("")
    lines.append("as read:")
    lines.append(to_text(lineage))
    if manifests:
        lines.append("")
        lines.append("traced to source:")
        lines.append(to_text(trace_through(lineage, manifests)))
    return "\n".join(lines) + "\n"


def write_static_lineage(registry: Registry, directory: str | Path) -> tuple[Path, ...]:
    """Write one static Lineage file per declared Case into `directory`.

    One file per Case, named `<case name>.txt`, so a diff points at the Case that moved.
    Returns the paths written, sorted. Overwrites; it is regenerated output, and a CI job
    that regenerates and diffs is the intended use.

    Written UTF-8 with explicit `\\n` line endings: the artifact is committed, and a
    regeneration on Windows that only changed the line endings would show every line of
    every file as modified.
    """
    target = Path(directory)
    target.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for case in registry.cases():
        path = target / f"{case.name}.txt"
        path.write_text(static_lineage(registry, case), encoding="utf-8", newline="\n")
        written.append(path)
    return tuple(sorted(written))


def write_manifests(registry: Registry, directory: str | Path) -> tuple[Path, ...]:
    """Write one Manifest per written Source into `directory`, as `<db>.<table>.json`.

    The writer `Manifest.from_json` was missing. A Manifest round-trips through JSON
    precisely so a reader in another process can trace through a written table without
    re-deriving it, and until something wrote one, that reader had no file to open and
    `Registry.resolve_column`'s reason for existing ("when a Manifest or a static Lineage
    artifact is read back from disk") described a workflow nothing provided.

    Derived from the Declarations with nothing running and no `run_date`, exactly like the
    static Lineage artifact beside it, so both are regenerated by the same command and
    diffed in the same review. Overwrites; regenerated output.

    Named by the written Source rather than by the producing Case, because that is the key a
    reader has: they hold a table name and want the Manifest for it.
    """
    from sqlcomposer import compile as compile_module  # local: see static_lineage

    target = Path(directory)
    target.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for case in registry.cases():
        if case.writes_to is None:
            continue
        source = registry.source(case.writes_to.qualified)
        manifest = manifest_for(registry, compile_module.plan(registry, case), source)
        path = target / f"{source.qualified}.json"
        path.write_text(manifest.to_json() + "\n", encoding="utf-8", newline="\n")
        written.append(path)
    return tuple(sorted(written))
